import { RoommateListing } from './types';

export const CITIES = [
  'ሁሉም ከተሞች (All Cities)',
  'አዲስ አበባ (Addis Ababa)',
  'አዳማ / ናዝሬት (Adama)',
  'ሐዋሳ (Hawassa)',
  'ባህር ዳር (Bahir Dar)',
  'ድሬዳዋ (Dire Dawa)',
  'መቀሌ (Mekelle)',
  'ጂማ (Jimma)',
  'ጎንደር (Gondar)',
  'ደሴ (Dessie)',
];

export const LOCATIONS_BY_CITY: Record<string, string[]> = {
  'ሁሉም ከተሞች (All Cities)': [
    'ሁሉም ሰፈሮች (All Sefers)',
    'ቦሌ (Bole)',
    'መገናኛ (Megenagna)',
    'ሲኤምሲ (CMC)',
    'አያት (Ayat)',
    'ሳርቤት (Sarbet)',
    'ካዛንቺስ (Kazanchis)',
    'ፒያሳ (Piassa)',
    'ጀሞ (Jemo)',
    'ሀያት (Hayat)',
    'ቀበና (Kebena)',
    'አራት ኪሎ (Arat Kilo)',
    'ፖስታ ቤት አካባቢ',
  ],
  'አዲስ አበባ (Addis Ababa)': [
    'ሁሉም ሰፈሮች (All Sefers)',
    'ቦሌ (Bole)',
    'መገናኛ (Megenagna)',
    'ሲኤምሲ (CMC)',
    'አያት (Ayat)',
    'ሳርቤት (Sarbet)',
    'ካዛንቺስ (Kazanchis)',
    'ፒያሳ (Piassa)',
    'ጀሞ (Jemo)',
    'ሀያት (Hayat)',
    'ቀበና (Kebena)',
    'አራት ኪሎ (Arat Kilo)',
    'ገርጂ (Gerji)',
    'ለቡ (Lebu)',
    'ተክለሃይማኖት (Teklehaymanot)',
  ],
  'አዳማ / ናዝሬት (Adama)': ['ሁሉም ሰፈሮች (All Sefers)', 'ፖስታ ቤት አካባቢ', 'ቦሌ አዳማ', '04 ቀበሌ', 'ፍራንክ', 'አባ ጅፋር'],
  'ሐዋሳ (Hawassa)': ['ሁሉም ሰፈሮች (All Sefers)', 'ፒያሳ ሐዋሳ', 'ታቦር', 'አሮጌው ገበያ', 'ሞኖፖል', 'ሚሌኒየም'],
  'ባህር ዳር (Bahir Dar)': ['ሁሉም ሰፈሮች (All Sefers)', 'ቀበሌ 04', 'ቀበሌ 11', 'ፔዳ', 'ዲያስፖራ ሰፈር', 'አባይ ማዶ'],
  'ድሬዳዋ (Dire Dawa)': ['ሁሉም ሰፈሮች (All Sefers)', 'ከዚራ', 'መጋላ', 'ሳብያን', 'አሸዋ ፕላዛ'],
  'መቀሌ (Mekelle)': ['ሁሉም ሰፈሮች (All Sefers)', 'ቀዳማይ ወያነ', '16 ቀበሌ', 'ዓዲ ሓቂ', 'ኩይሓ'],
  'ጂማ (Jimma)': ['ሁሉም ሰፈሮች (All Sefers)', 'መርካቶ ጂማ', 'ቦሌ ጂማ', 'አዋሮ', 'ኸርሚ'],
  'ጎንደር (Gondar)': ['ሁሉም ሰፈሮች (All Sefers)', 'ፒያሳ ጎንደር', 'አዘዞ', 'ማራኪ', 'አርዳ'],
  'ደሴ (Dessie)': ['ሁሉም ሰፈሮች (All Sefers)', 'ፒያሳ ደሴ', 'ሆጤ', 'አራዳ', 'ሰኞ ገበያ'],
};

export const HOUSE_TYPES = [
  'ሁሉም የቤት አይነቶች (All Types)',
  'ኮንዶሚኒየም (Condominium)',
  'አፓርታማ (Apartment)',
  'ቪላ ቤት (Villa)',
  'አገልግሎት / ስቱዲዮ (Studio / Service)',
];

export const ROOMS_COUNTS: (number | 'ALL')[] = ['ALL', 1, 2, 3, 4];

export const LIFESTYLE_TAGS = [
  'አያጨስም (Non-smoker)',
  'ጸጥታ የሚወድ (Quiet)',
  'ተማሪ (Student)',
  'ሰራተኛ (Professional)',
  'ጽዳት የሚወድ (Clean)',
  'ማታ ማታ የሚያጠና (Night Owl)',
  'ጠዋት የሚነሳ (Early Bird)',
  'ቤት እንስሳ የሌለው (No Pets)',
];

export const AMENITIES_LIST = [
  'ዋይፋይ (WiFi)',
  'ውሃ ሁልጊዜ ያለ (24/7 Water)',
  'የኤሌክትሪክ ማብሰያ (Electric Stove)',
  'ፓርኪንግ (Parking)',
  'ፀጥታ ያለበት ግቢ (Quiet Compound)',
  'በረንዳ (Balcony)',
  'የልብስ ማጠቢያ (Washing Machine)',
  'ሞቀ ውሃ (Hot Shower)',
];

export const SAMPLE_PRESETS: RoommateListing[] = [
  {
    id: '1',
    name: 'አበበ ታደሰ (Abebe T.)',
    age: 26,
    gender: 'ወንድ (Male)',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    role: 'ክፍል አለኝ (Have a Room)',
    country: 'ኢትዮጵያ (Ethiopia)',
    city: 'አዲስ አበባ (Addis Ababa)',
    location: 'ቦሌ (Bole)',
    exactLocation: 'ቦሌ አትላስ፣ ሆቴል አጠገብ ኮንዶሚኒየም ብሎክ 14',
    houseType: 'ኮንዶሚኒየም (Condominium)',
    roomsCount: 2,
    budget: 8500,
    occupation: 'የሶፍትዌር ኢንጂነር (Software Engineer)',
    lifestyle: ['አያጨስም (Non-smoker)', 'ሰራተኛ (Professional)', 'ጽዳት የሚወድ (Clean)'],
    description: 'ቦሌ አትላስ አካባቢ 1 መኝታ ቤት ያለው ሰፊ ኮንዶሚኒየም አለኝ። ዋይፋይ እና ቋሚ የውሃ መስመር አለው። አብሮኝ ኪራይ የሚካፈል ሰላማዊ እና ንጹህ ሰው እፈልጋለሁ።',
    phone: '+251 911 234 567',
    telegram: '@abebe_t',
    postedDate: 'ከ 2 ቀናት በፊት (2 days ago)',
    isSample: true,
    roomDetails: {
      bedrooms: 2,
      bathrooms: 1,
      amenities: ['ዋይፋይ (WiFi)', 'ውሃ ሁልጊዜ ያለ (24/7 Water)', 'ሞቀ ውሃ (Hot Shower)', 'በረንዳ (Balcony)'],
      images: [
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
      ],
    },
  },
  {
    id: '2',
    name: 'ሄለን ሰለሞን (Helen S.)',
    age: 23,
    gender: 'ሴት (Female)',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    role: 'ፈልጋለሁ (Looking for Room)',
    country: 'ኢትዮጵያ (Ethiopia)',
    city: 'አዲስ አበባ (Addis Ababa)',
    location: 'መገናኛ (Megenagna)',
    exactLocation: 'መገናኛ ሲኤምሲ መንገድ፣ ማራቶን ህንጻ ጀርባ',
    houseType: 'አፓርታማ (Apartment)',
    roomsCount: 2,
    budget: 6000,
    occupation: 'የአዲስ አበባ ዩኒቨርሲቲ ተማሪ (AAU Student)',
    lifestyle: ['ጸጥታ የሚወድ (Quiet)', 'ተማሪ (Student)', 'ጠዋት የሚነሳ (Early Bird)'],
    description: 'አራት ኪሎ ወይም መገናኛ አካባቢ ከአንዲት ሴት ጋር ክፍል መካፈል እፈልጋለሁ። ለትምህርት ቅርብ የሆነ እና ጸጥታ ያለው ቦታ ቢሆን እመርጣለሁ።',
    phone: '+251 922 345 678',
    telegram: '@helen_sola',
    postedDate: 'ትላንት (Yesterday)',
    isSample: true,
  },
  {
    id: '3',
    name: 'ዳዊት በቀለ (Dawit B.)',
    age: 29,
    gender: 'ወንድ (Male)',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    role: 'ክፍል አለኝ (Have a Room)',
    country: 'ኢትዮጵያ (Ethiopia)',
    city: 'አዲስ አበባ (Addis Ababa)',
    location: 'ሲኤምሲ (CMC)',
    exactLocation: 'ሲኤምሲ ሚካኤል ቤተክርስቲያን ጀርባ ቪላ ግቢ',
    houseType: 'አገልግሎት / ስቱዲዮ (Studio / Service)',
    roomsCount: 1,
    budget: 7000,
    occupation: 'ባንክ ሰራተኛ (Banker)',
    lifestyle: ['ሰራተኛ (Professional)', 'አያጨስም (Non-smoker)', 'ጸጥታ የሚወድ (Quiet)'],
    description: 'ሲኤምሲ ሚካኤል አካባቢ ቆንጆ ግቢ ውስጥ የሚገኝ ሰፊ አገልግሎት ቤት። ራሱን የቻለ ሽንት ቤት እና ማብሰያ አለው። ወጪ ለመቀነስ 1 ሰው እፈልጋለሁ።',
    phone: '+251 933 456 789',
    telegram: '@dawit_bank',
    postedDate: 'ከ 4 ቀናት በፊት (4 days ago)',
    isSample: true,
    roomDetails: {
      bedrooms: 1,
      bathrooms: 1,
      amenities: ['ፓርኪንግ (Parking)', 'ውሃ ሁልጊዜ ያለ (24/7 Water)', 'ፀጥታ ያለበት ግቢ (Quiet Compound)'],
      images: [
        'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80',
      ],
    },
  },
  {
    id: '4',
    name: 'ማርታ ኃይሉ (Martha H.)',
    age: 25,
    gender: 'ሴት (Female)',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
    role: 'ክፍል አለኝ (Have a Room)',
    country: 'ኢትዮጵያ (Ethiopia)',
    city: 'አዲስ አበባ (Addis Ababa)',
    location: 'ሳርቤት (Sarbet)',
    exactLocation: 'ሳርቤት ፑሽኪን አደባባይ፣ 3ኛ ፎቅ አፓርታማ',
    houseType: 'አፓርታማ (Apartment)',
    roomsCount: 3,
    budget: 9000,
    occupation: 'ግራፊክስ ዲዛይነር (Graphic Designer)',
    lifestyle: ['ጽዳት የሚወድ (Clean)', 'ሰራተኛ (Professional)', 'ቤት እንስሳ የሌለው (No Pets)'],
    description: 'ሳርቤት ፑሽኪን አደባባይ አጠገብ ዘመናዊ አፓርታማ። መኝታ ቤቱ ሁለት አልጋ ይይዛል። በጣም ደህንነቱ የተጠበቀ አካባቢ ነው፣ ከአንዲት ሴት ጋር መካፈል እፈልጋለሁ።',
    phone: '+251 944 567 890',
    telegram: '@marthadesign',
    postedDate: 'ዛሬ ጠዋት (Today)',
    isSample: true,
    roomDetails: {
      bedrooms: 2,
      bathrooms: 1,
      amenities: ['ዋይፋይ (WiFi)', 'ሞቀ ውሃ (Hot Shower)', 'የልብስ ማጠቢያ (Washing Machine)', 'በረንዳ (Balcony)'],
      images: [
        'https://images.unsplash.com/photo-1502005229762-bf1b461e9b47?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80',
      ],
    },
  },
  {
    id: '5',
    name: 'ዮናስ ከበደ (Yonas K.)',
    age: 24,
    gender: 'ወንድ (Male)',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    role: 'ፈልጋለሁ (Looking for Room)',
    country: 'ኢትዮጵያ (Ethiopia)',
    city: 'አዲስ አበባ (Addis Ababa)',
    location: 'አያት (Ayat)',
    exactLocation: 'አያት 40/60 ኮንዶሚኒየም አካባቢ',
    houseType: 'ኮንዶሚኒየም (Condominium)',
    roomsCount: 2,
    budget: 5000,
    occupation: 'አካውንታንት (Accountant)',
    lifestyle: ['አያጨስም (Non-smoker)', 'ሰራተኛ (Professional)'],
    description: 'አያት ኮንዶሚኒየም ወይም ሲኤምሲ አካባቢ ቤት መካፈል የሚፈልግ ወንድ እፈልጋለሁ። በሰዓቱ ኪራይ የምከፍል ሰላማዊ ሰው ነኝ።',
    phone: '+251 955 678 901',
    telegram: '@yonas_keb',
    postedDate: 'ከ 3 ቀናት በፊት (3 days ago)',
    isSample: true,
  },
  {
    id: '6',
    name: 'ትዕግስት አለሙ (Tigist A.)',
    age: 27,
    gender: 'ሴት (Female)',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
    role: 'ፈልጋለሁ (Looking for Room)',
    country: 'ኢትዮጵያ (Ethiopia)',
    city: 'አዳማ / ናዝሬት (Adama)',
    location: 'ፖስታ ቤት አካባቢ',
    exactLocation: 'አዳማ ፖስታ ቤት አጠገብ ዋና መንገድ ላይ',
    houseType: 'አፓርታማ (Apartment)',
    roomsCount: 2,
    budget: 4500,
    occupation: 'የ NGO ሰራተኛ (NGO Worker)',
    lifestyle: ['ጸጥታ የሚወድ (Quiet)', 'ጽዳት የሚወድ (Clean)', 'ጠዋት የሚነሳ (Early Bird)'],
    description: 'አዳማ ከተማ ውስጥ ከሴት ጋር ክፍል መካፈል እፈልጋለሁ። ንጹህ ቤት እና ጥሩ ጎረቤት ያለው ቢሆን።',
    phone: '+251 966 789 012',
    postedDate: 'ከ 5 ቀናት በፊት (5 days ago)',
    isSample: true,
  },
];

// Initial listings start empty so the user starts with a clean production slate
export const INITIAL_LISTINGS: RoommateListing[] = [];
